export const CATEGORIES = [
  "Administrative",
  "Agriculture",
  "Biota",
  "Boundaries",
  "Budget",
  "Business & Economy",
  "Demographic",
  "Education",
  "Elevation",
  "Energy and Environment",
  "Geoscientific",
  "Government",
  "Health and Human Services",
  "Historic",
  "Housing",
  "Hydrology",
  "Imagery",
  "Location",
  "Military",
  "Planning",
  "Public Safety",
  "Society",
  "Structure",
  "Transportation",
  "Utility",
  "Weather",
].sort();

